export * from './aPIPurchaseDetailReportService.service';
import { APIPurchaseDetailReportServiceService } from './aPIPurchaseDetailReportService.service';
export * from './aPIPurchaseDetailService.service';
import { APIPurchaseDetailServiceService } from './aPIPurchaseDetailService.service';
export * from './aPITypeService.service';
import { APITypeServiceService } from './aPITypeService.service';
export * from './abstractItemService.service';
import { AbstractItemServiceService } from './abstractItemService.service';
export * from './abstractLedgerService.service';
import { AbstractLedgerServiceService } from './abstractLedgerService.service';
export * from './abstractSaleTxService.service';
import { AbstractSaleTxServiceService } from './abstractSaleTxService.service';
export * from './abstractTransactionService.service';
import { AbstractTransactionServiceService } from './abstractTransactionService.service';
export * from './abstractVoucherTxService.service';
import { AbstractVoucherTxServiceService } from './abstractVoucherTxService.service';
export * from './accountingBillPrintService.service';
import { AccountingBillPrintServiceService } from './accountingBillPrintService.service';
export * from './accountingConvertTransactionService.service';
import { AccountingConvertTransactionServiceService } from './accountingConvertTransactionService.service';
export * from './accountingSMSPrefTemplateListService.service';
import { AccountingSMSPrefTemplateListServiceService } from './accountingSMSPrefTemplateListService.service';
export * from './accountingSMSService.service';
import { AccountingSMSServiceService } from './accountingSMSService.service';
export * from './accountingTxReportService.service';
import { AccountingTxReportServiceService } from './accountingTxReportService.service';
export * from './addressTypeService.service';
import { AddressTypeServiceService } from './addressTypeService.service';
export * from './applicationResourceService.service';
import { ApplicationResourceServiceService } from './applicationResourceService.service';
export * from './applicationUserPrivilegeService.service';
import { ApplicationUserPrivilegeServiceService } from './applicationUserPrivilegeService.service';
export * from './areaImportService.service';
import { AreaImportServiceService } from './areaImportService.service';
export * from './areaService.service';
import { AreaServiceService } from './areaService.service';
export * from './assetService.service';
import { AssetServiceService } from './assetService.service';
export * from './attributeGroupService.service';
import { AttributeGroupServiceService } from './attributeGroupService.service';
export * from './attributeService.service';
import { AttributeServiceService } from './attributeService.service';
export * from './backupService.service';
import { BackupServiceService } from './backupService.service';
export * from './bagService.service';
import { BagServiceService } from './bagService.service';
export * from './bagsDetailsReportService.service';
import { BagsDetailsReportServiceService } from './bagsDetailsReportService.service';
export * from './bagsDetailsReportService2.service';
import { BagsDetailsReportService2Service } from './bagsDetailsReportService2.service';
export * from './balanceSheetReportService.service';
import { BalanceSheetReportServiceService } from './balanceSheetReportService.service';
export * from './bankEntryRegisterReportService.service';
import { BankEntryRegisterReportServiceService } from './bankEntryRegisterReportService.service';
export * from './bankReconciliationReportService.service';
import { BankReconciliationReportServiceService } from './bankReconciliationReportService.service';
export * from './bankTxService.service';
import { BankTxServiceService } from './bankTxService.service';
export * from './barCodePrintConfigurationService.service';
import { BarCodePrintConfigurationServiceService } from './barCodePrintConfigurationService.service';
export * from './barCodeService.service';
import { BarCodeServiceService } from './barCodeService.service';
export * from './barcodePrintSettingService.service';
import { BarcodePrintSettingServiceService } from './barcodePrintSettingService.service';
export * from './baseSMSPrefTemplateListService.service';
import { BaseSMSPrefTemplateListServiceService } from './baseSMSPrefTemplateListService.service';
export * from './billingClassificationService.service';
import { BillingClassificationServiceService } from './billingClassificationService.service';
export * from './billingGroupService.service';
import { BillingGroupServiceService } from './billingGroupService.service';
export * from './birthdayAndAnniversaryReportService.service';
import { BirthdayAndAnniversaryReportServiceService } from './birthdayAndAnniversaryReportService.service';
export * from './bonusReportService.service';
import { BonusReportServiceService } from './bonusReportService.service';
export * from './brokerReportService.service';
import { BrokerReportServiceService } from './brokerReportService.service';
export * from './brokerService.service';
import { BrokerServiceService } from './brokerService.service';
export * from './cacheService.service';
import { CacheServiceService } from './cacheService.service';
export * from './capitalAccountReportService.service';
import { CapitalAccountReportServiceService } from './capitalAccountReportService.service';
export * from './cashBookReportService.service';
import { CashBookReportServiceService } from './cashBookReportService.service';
export * from './cashInHandReportService.service';
import { CashInHandReportServiceService } from './cashInHandReportService.service';
export * from './cashSaleReportService.service';
import { CashSaleReportServiceService } from './cashSaleReportService.service';
export * from './challanInwardTxService.service';
import { ChallanInwardTxServiceService } from './challanInwardTxService.service';
export * from './challanTxService.service';
import { ChallanTxServiceService } from './challanTxService.service';
export * from './chemistItemService.service';
import { ChemistItemServiceService } from './chemistItemService.service';
export * from './chemistSaleTxAttributesService.service';
import { ChemistSaleTxAttributesServiceService } from './chemistSaleTxAttributesService.service';
export * from './chequeBookService.service';
import { ChequeBookServiceService } from './chequeBookService.service';
export * from './chequeConfigurationService.service';
import { ChequeConfigurationServiceService } from './chequeConfigurationService.service';
export * from './chequeDetailReportService.service';
import { ChequeDetailReportServiceService } from './chequeDetailReportService.service';
export * from './chequeDetailService.service';
import { ChequeDetailServiceService } from './chequeDetailService.service';
export * from './chequeSearchReportService.service';
import { ChequeSearchReportServiceService } from './chequeSearchReportService.service';
export * from './choiceListService.service';
import { ChoiceListServiceService } from './choiceListService.service';
export * from './cityService.service';
import { CityServiceService } from './cityService.service';
export * from './closingRateService.service';
import { ClosingRateServiceService } from './closingRateService.service';
export * from './code128Service.service';
import { Code128ServiceService } from './code128Service.service';
export * from './commissionReportService.service';
import { CommissionReportServiceService } from './commissionReportService.service';
export * from './commissionSaleReportService.service';
import { CommissionSaleReportServiceService } from './commissionSaleReportService.service';
export * from './companyPlanService.service';
import { CompanyPlanServiceService } from './companyPlanService.service';
export * from './companyPreferenceService.service';
import { CompanyPreferenceServiceService } from './companyPreferenceService.service';
export * from './companyService.service';
import { CompanyServiceService } from './companyService.service';
export * from './compareTaxClassWithItemMasterReportService.service';
import { CompareTaxClassWithItemMasterReportServiceService } from './compareTaxClassWithItemMasterReportService.service';
export * from './consumptionItemDetailReportService.service';
import { ConsumptionItemDetailReportServiceService } from './consumptionItemDetailReportService.service';
export * from './consumptionSummaryReportService.service';
import { ConsumptionSummaryReportServiceService } from './consumptionSummaryReportService.service';
export * from './consumptionSummaryReportService2.service';
import { ConsumptionSummaryReportService2Service } from './consumptionSummaryReportService2.service';
export * from './consumptionTxService.service';
import { ConsumptionTxServiceService } from './consumptionTxService.service';
export * from './contactAddressService.service';
import { ContactAddressServiceService } from './contactAddressService.service';
export * from './contactService.service';
import { ContactServiceService } from './contactService.service';
export * from './convertProcurementTxPurchaseEnquriyTxService.service';
import { ConvertProcurementTxPurchaseEnquriyTxServiceService } from './convertProcurementTxPurchaseEnquriyTxService.service';
export * from './convertPurchaseEnquiryTransactionService.service';
import { ConvertPurchaseEnquiryTransactionServiceService } from './convertPurchaseEnquiryTransactionService.service';
export * from './convertPurchaseEnquiryTxService.service';
import { ConvertPurchaseEnquiryTxServiceService } from './convertPurchaseEnquiryTxService.service';
export * from './convertSaleEnquiryTxService.service';
import { ConvertSaleEnquiryTxServiceService } from './convertSaleEnquiryTxService.service';
export * from './convertTransactionService.service';
import { ConvertTransactionServiceService } from './convertTransactionService.service';
export * from './costCenterBreakUpMonthlyLedgerGroupWiseRegisterService.service';
import { CostCenterBreakUpMonthlyLedgerGroupWiseRegisterServiceService } from './costCenterBreakUpMonthlyLedgerGroupWiseRegisterService.service';
export * from './costCenterBreakUpMonthlyLedgerWiseRegisterService.service';
import { CostCenterBreakUpMonthlyLedgerWiseRegisterServiceService } from './costCenterBreakUpMonthlyLedgerWiseRegisterService.service';
export * from './costCenterBreakUpRegisterService.service';
import { CostCenterBreakUpRegisterServiceService } from './costCenterBreakUpRegisterService.service';
export * from './costCenterLedgerWiseRegisterService.service';
import { CostCenterLedgerWiseRegisterServiceService } from './costCenterLedgerWiseRegisterService.service';
export * from './costCenterLineService.service';
import { CostCenterLineServiceService } from './costCenterLineService.service';
export * from './costCenterMonthlySummaryRegisterService.service';
import { CostCenterMonthlySummaryRegisterServiceService } from './costCenterMonthlySummaryRegisterService.service';
export * from './costCenterService.service';
import { CostCenterServiceService } from './costCenterService.service';
export * from './costCenterSummaryRegisterService.service';
import { CostCenterSummaryRegisterServiceService } from './costCenterSummaryRegisterService.service';
export * from './costCenterVouchersRegisterService.service';
import { CostCenterVouchersRegisterServiceService } from './costCenterVouchersRegisterService.service';
export * from './countryService.service';
import { CountryServiceService } from './countryService.service';
export * from './crNoteInvTxService.service';
import { CrNoteInvTxServiceService } from './crNoteInvTxService.service';
export * from './crNoteRInvTxService.service';
import { CrNoteRInvTxServiceService } from './crNoteRInvTxService.service';
export * from './crNoteTxService.service';
import { CrNoteTxServiceService } from './crNoteTxService.service';
export * from './crateRegisterReportService.service';
import { CrateRegisterReportServiceService } from './crateRegisterReportService.service';
export * from './createPOFromStockReportService.service';
import { CreatePOFromStockReportServiceService } from './createPOFromStockReportService.service';
export * from './createRegisterReportService.service';
import { CreateRegisterReportServiceService } from './createRegisterReportService.service';
export * from './credentialsService.service';
import { CredentialsServiceService } from './credentialsService.service';
export * from './currentBalanceReportService.service';
import { CurrentBalanceReportServiceService } from './currentBalanceReportService.service';
export * from './customNamesForItemService.service';
import { CustomNamesForItemServiceService } from './customNamesForItemService.service';
export * from './customerContactService.service';
import { CustomerContactServiceService } from './customerContactService.service';
export * from './customerTicketService.service';
import { CustomerTicketServiceService } from './customerTicketService.service';
export * from './dailyEntryReportService.service';
import { DailyEntryReportServiceService } from './dailyEntryReportService.service';
export * from './dailyMilkCrateStockSummaryService.service';
import { DailyMilkCrateStockSummaryServiceService } from './dailyMilkCrateStockSummaryService.service';
export * from './dailyMilkPurchaseReportService.service';
import { DailyMilkPurchaseReportServiceService } from './dailyMilkPurchaseReportService.service';
export * from './dataImportHistoryService.service';
import { DataImportHistoryServiceService } from './dataImportHistoryService.service';
export * from './databaseService.service';
import { DatabaseServiceService } from './databaseService.service';
export * from './dayBookService.service';
import { DayBookServiceService } from './dayBookService.service';
export * from './dayWiseLedgerBalanceReportService.service';
import { DayWiseLedgerBalanceReportServiceService } from './dayWiseLedgerBalanceReportService.service';
export * from './dayWiseLedgerGroupBalanceReportService.service';
import { DayWiseLedgerGroupBalanceReportServiceService } from './dayWiseLedgerGroupBalanceReportService.service';
export * from './deleteAllTransactionService.service';
import { DeleteAllTransactionServiceService } from './deleteAllTransactionService.service';
export * from './deleteDataAndConvertBalanceToOpeningService.service';
import { DeleteDataAndConvertBalanceToOpeningServiceService } from './deleteDataAndConvertBalanceToOpeningService.service';
export * from './deleteVerificationService.service';
import { DeleteVerificationServiceService } from './deleteVerificationService.service';
export * from './deletedTransactionReportService.service';
import { DeletedTransactionReportServiceService } from './deletedTransactionReportService.service';
export * from './deletedTransactionService.service';
import { DeletedTransactionServiceService } from './deletedTransactionService.service';
export * from './departmentService.service';
import { DepartmentServiceService } from './departmentService.service';
export * from './depreciationChartReportService.service';
import { DepreciationChartReportServiceService } from './depreciationChartReportService.service';
export * from './diagnosticToolService.service';
import { DiagnosticToolServiceService } from './diagnosticToolService.service';
export * from './discountService.service';
import { DiscountServiceService } from './discountService.service';
export * from './districtService.service';
import { DistrictServiceService } from './districtService.service';
export * from './doctorPrescriptionReportService.service';
import { DoctorPrescriptionReportServiceService } from './doctorPrescriptionReportService.service';
export * from './doctorService.service';
import { DoctorServiceService } from './doctorService.service';
export * from './documentService.service';
import { DocumentServiceService } from './documentService.service';
export * from './drNoteInvTxService.service';
import { DrNoteInvTxServiceService } from './drNoteInvTxService.service';
export * from './drNoteRInvTxService.service';
import { DrNoteRInvTxServiceService } from './drNoteRInvTxService.service';
export * from './drNoteTxService.service';
import { DrNoteTxServiceService } from './drNoteTxService.service';
export * from './drugCompositionService.service';
import { DrugCompositionServiceService } from './drugCompositionService.service';
export * from './dueChequesReportService.service';
import { DueChequesReportServiceService } from './dueChequesReportService.service';
export * from './eComOrderService.service';
import { EComOrderServiceService } from './eComOrderService.service';
export * from './eInvoiceHostedService.service';
import { EInvoiceHostedServiceService } from './eInvoiceHostedService.service';
export * from './eInvoiceService.service';
import { EInvoiceServiceService } from './eInvoiceService.service';
export * from './emailMultipleReportsUtilService.service';
import { EmailMultipleReportsUtilServiceService } from './emailMultipleReportsUtilService.service';
export * from './emailUtilService.service';
import { EmailUtilServiceService } from './emailUtilService.service';
export * from './errorLogReportService.service';
import { ErrorLogReportServiceService } from './errorLogReportService.service';
export * from './errorLogService.service';
import { ErrorLogServiceService } from './errorLogService.service';
export * from './eventService.service';
import { EventServiceService } from './eventService.service';
export * from './ewayBillService.service';
import { EwayBillServiceService } from './ewayBillService.service';
export * from './expenseTxService.service';
import { ExpenseTxServiceService } from './expenseTxService.service';
export * from './expensesRegisterReportService.service';
import { ExpensesRegisterReportServiceService } from './expensesRegisterReportService.service';
export * from './expiringItemsReportService.service';
import { ExpiringItemsReportServiceService } from './expiringItemsReportService.service';
export * from './exportDataService.service';
import { ExportDataServiceService } from './exportDataService.service';
export * from './favouriteURLService.service';
import { FavouriteURLServiceService } from './favouriteURLService.service';
export * from './featureRequestService.service';
import { FeatureRequestServiceService } from './featureRequestService.service';
export * from './fileSharingService.service';
import { FileSharingServiceService } from './fileSharingService.service';
export * from './findNameOrVoucherService.service';
import { FindNameOrVoucherServiceService } from './findNameOrVoucherService.service';
export * from './gSTINVerificationHostedService.service';
import { GSTINVerificationHostedServiceService } from './gSTINVerificationHostedService.service';
export * from './gSTINVerificationService.service';
import { GSTINVerificationServiceService } from './gSTINVerificationService.service';
export * from './gSTR3ReportService.service';
import { GSTR3ReportServiceService } from './gSTR3ReportService.service';
export * from './gSTR4AReportService.service';
import { GSTR4AReportServiceService } from './gSTR4AReportService.service';
export * from './gSTReportService.service';
import { GSTReportServiceService } from './gSTReportService.service';
export * from './gatePassDetailService.service';
import { GatePassDetailServiceService } from './gatePassDetailService.service';
export * from './gatePassInTxService.service';
import { GatePassInTxServiceService } from './gatePassInTxService.service';
export * from './gatePassOutTxService.service';
import { GatePassOutTxServiceService } from './gatePassOutTxService.service';
export * from './gatePassOutwardTxService.service';
import { GatePassOutwardTxServiceService } from './gatePassOutwardTxService.service';
export * from './generateInvoiceService.service';
import { GenerateInvoiceServiceService } from './generateInvoiceService.service';
export * from './genericReportService.service';
import { GenericReportServiceService } from './genericReportService.service';
export * from './grainAgentBillPrintService.service';
import { GrainAgentBillPrintServiceService } from './grainAgentBillPrintService.service';
export * from './grainAgentImportService.service';
import { GrainAgentImportServiceService } from './grainAgentImportService.service';
export * from './grainAgentItemRegisterReportService.service';
import { GrainAgentItemRegisterReportServiceService } from './grainAgentItemRegisterReportService.service';
export * from './grainAgentItemService.service';
import { GrainAgentItemServiceService } from './grainAgentItemService.service';
export * from './grainAgentKMSReportService.service';
import { GrainAgentKMSReportServiceService } from './grainAgentKMSReportService.service';
export * from './grainAgentLocalNameUtilService.service';
import { GrainAgentLocalNameUtilServiceService } from './grainAgentLocalNameUtilService.service';
export * from './grainAgentRMSReportService.service';
import { GrainAgentRMSReportServiceService } from './grainAgentRMSReportService.service';
export * from './grainAgentStockSummaryReportService.service';
import { GrainAgentStockSummaryReportServiceService } from './grainAgentStockSummaryReportService.service';
export * from './grainAgentStockSummaryReportService2.service';
import { GrainAgentStockSummaryReportService2Service } from './grainAgentStockSummaryReportService2.service';
export * from './grainPurchaseTxService.service';
import { GrainPurchaseTxServiceService } from './grainPurchaseTxService.service';
export * from './grainSaleTxService.service';
import { GrainSaleTxServiceService } from './grainSaleTxService.service';
export * from './heapRegisterService.service';
import { HeapRegisterServiceService } from './heapRegisterService.service';
export * from './hisabKhataService.service';
import { HisabKhataServiceService } from './hisabKhataService.service';
export * from './hsnWiseSummaryReportService.service';
import { HsnWiseSummaryReportServiceService } from './hsnWiseSummaryReportService.service';
export * from './hypothecationDetailReportService.service';
import { HypothecationDetailReportServiceService } from './hypothecationDetailReportService.service';
export * from './iFormDetailReportService.service';
import { IFormDetailReportServiceService } from './iFormDetailReportService.service';
export * from './iFormTxService.service';
import { IFormTxServiceService } from './iFormTxService.service';
export * from './importBankEntryFromExelService.service';
import { ImportBankEntryFromExelServiceService } from './importBankEntryFromExelService.service';
export * from './importMilkJournalEntryFromExcelUtilService.service';
import { ImportMilkJournalEntryFromExcelUtilServiceService } from './importMilkJournalEntryFromExcelUtilService.service';
export * from './importMilkPurchaseFromExcelUtilService.service';
import { ImportMilkPurchaseFromExcelUtilServiceService } from './importMilkPurchaseFromExcelUtilService.service';
export * from './importTransactionExcelUtilService.service';
import { ImportTransactionExcelUtilServiceService } from './importTransactionExcelUtilService.service';
export * from './inActiveLedgersReportService.service';
import { InActiveLedgersReportServiceService } from './inActiveLedgersReportService.service';
export * from './innoventryCustomerService.service';
import { InnoventryCustomerServiceService } from './innoventryCustomerService.service';
export * from './innoventryEditionInfoService.service';
import { InnoventryEditionInfoServiceService } from './innoventryEditionInfoService.service';
export * from './innoventryPublicService.service';
import { InnoventryPublicServiceService } from './innoventryPublicService.service';
export * from './interestReportService.service';
import { InterestReportServiceService } from './interestReportService.service';
export * from './interestTxService.service';
import { InterestTxServiceService } from './interestTxService.service';
export * from './inventoryAllBillPrintService.service';
import { InventoryAllBillPrintServiceService } from './inventoryAllBillPrintService.service';
export * from './inventoryBillingGroupImportUtilService.service';
import { InventoryBillingGroupImportUtilServiceService } from './inventoryBillingGroupImportUtilService.service';
export * from './inventoryFinancialReportService.service';
import { InventoryFinancialReportServiceService } from './inventoryFinancialReportService.service';
export * from './inventorySMSPrefTemplateListService.service';
import { InventorySMSPrefTemplateListServiceService } from './inventorySMSPrefTemplateListService.service';
export * from './inventoryTransactionDashboardReportService.service';
import { InventoryTransactionDashboardReportServiceService } from './inventoryTransactionDashboardReportService.service';
export * from './inventoryTxReportService.service';
import { InventoryTxReportServiceService } from './inventoryTxReportService.service';
export * from './inventoryTxReportService2.service';
import { InventoryTxReportService2Service } from './inventoryTxReportService2.service';
export * from './inventoryTxTaxConfigurationService.service';
import { InventoryTxTaxConfigurationServiceService } from './inventoryTxTaxConfigurationService.service';
export * from './inventoryTxVoucherReportService.service';
import { InventoryTxVoucherReportServiceService } from './inventoryTxVoucherReportService.service';
export * from './inwardQuotationTxReportService.service';
import { InwardQuotationTxReportServiceService } from './inwardQuotationTxReportService.service';
export * from './inwardQuotationTxService.service';
import { InwardQuotationTxServiceService } from './inwardQuotationTxService.service';
export * from './itemAttributeGroupLineService.service';
import { ItemAttributeGroupLineServiceService } from './itemAttributeGroupLineService.service';
export * from './itemAttributeSearchReportService.service';
import { ItemAttributeSearchReportServiceService } from './itemAttributeSearchReportService.service';
export * from './itemBatchService.service';
import { ItemBatchServiceService } from './itemBatchService.service';
export * from './itemDiscountService.service';
import { ItemDiscountServiceService } from './itemDiscountService.service';
export * from './itemEComService.service';
import { ItemEComServiceService } from './itemEComService.service';
export * from './itemGroupEComService.service';
import { ItemGroupEComServiceService } from './itemGroupEComService.service';
export * from './itemGroupQCParamReqValueService.service';
import { ItemGroupQCParamReqValueServiceService } from './itemGroupQCParamReqValueService.service';
export * from './itemGroupService.service';
import { ItemGroupServiceService } from './itemGroupService.service';
export * from './itemGroupWiseTradingAccountReportService.service';
import { ItemGroupWiseTradingAccountReportServiceService } from './itemGroupWiseTradingAccountReportService.service';
export * from './itemHistoryReportService.service';
import { ItemHistoryReportServiceService } from './itemHistoryReportService.service';
export * from './itemImportExportUtilService.service';
import { ItemImportExportUtilServiceService } from './itemImportExportUtilService.service';
export * from './itemLicenseKeyService.service';
import { ItemLicenseKeyServiceService } from './itemLicenseKeyService.service';
export * from './itemLicenseReportService.service';
import { ItemLicenseReportServiceService } from './itemLicenseReportService.service';
export * from './itemLineService.service';
import { ItemLineServiceService } from './itemLineService.service';
export * from './itemPurchaseByLedgerSummaryReportService.service';
import { ItemPurchaseByLedgerSummaryReportServiceService } from './itemPurchaseByLedgerSummaryReportService.service';
export * from './itemPurchaseRateAnalysisService.service';
import { ItemPurchaseRateAnalysisServiceService } from './itemPurchaseRateAnalysisService.service';
export * from './itemPurchaseRateVariationAnalysisReportService.service';
import { ItemPurchaseRateVariationAnalysisReportServiceService } from './itemPurchaseRateVariationAnalysisReportService.service';
export * from './itemQCParamReqValueService.service';
import { ItemQCParamReqValueServiceService } from './itemQCParamReqValueService.service';
export * from './itemRegisterForLedgerReportService.service';
import { ItemRegisterForLedgerReportServiceService } from './itemRegisterForLedgerReportService.service';
export * from './itemRegisterReportService.service';
import { ItemRegisterReportServiceService } from './itemRegisterReportService.service';
export * from './itemSaleSummaryReportService.service';
import { ItemSaleSummaryReportServiceService } from './itemSaleSummaryReportService.service';
export * from './itemSchemeLineService.service';
import { ItemSchemeLineServiceService } from './itemSchemeLineService.service';
export * from './itemSchemeService.service';
import { ItemSchemeServiceService } from './itemSchemeService.service';
export * from './itemSearchEcomService.service';
import { ItemSearchEcomServiceService } from './itemSearchEcomService.service';
export * from './itemSearchService.service';
import { ItemSearchServiceService } from './itemSearchService.service';
export * from './itemService.service';
import { ItemServiceService } from './itemService.service';
export * from './itemSupplierRateService.service';
import { ItemSupplierRateServiceService } from './itemSupplierRateService.service';
export * from './itemTicketDetailsService.service';
import { ItemTicketDetailsServiceService } from './itemTicketDetailsService.service';
export * from './itemTransactionParameterService.service';
import { ItemTransactionParameterServiceService } from './itemTransactionParameterService.service';
export * from './itemTransactionRegisterReportService.service';
import { ItemTransactionRegisterReportServiceService } from './itemTransactionRegisterReportService.service';
export * from './itemWiseLedgerSummaryReportService.service';
import { ItemWiseLedgerSummaryReportServiceService } from './itemWiseLedgerSummaryReportService.service';
export * from './itemWiseStockLocationRegisterService.service';
import { ItemWiseStockLocationRegisterServiceService } from './itemWiseStockLocationRegisterService.service';
export * from './jFormDetailReportService.service';
import { JFormDetailReportServiceService } from './jFormDetailReportService.service';
export * from './jFormTxService.service';
import { JFormTxServiceService } from './jFormTxService.service';
export * from './jobWorkTxService.service';
import { JobWorkTxServiceService } from './jobWorkTxService.service';
export * from './journalRegisterReportService.service';
import { JournalRegisterReportServiceService } from './journalRegisterReportService.service';
export * from './journalTxService.service';
import { JournalTxServiceService } from './journalTxService.service';
export * from './lastTransactionInfoService.service';
import { LastTransactionInfoServiceService } from './lastTransactionInfoService.service';
export * from './ledgerAttributesService.service';
import { LedgerAttributesServiceService } from './ledgerAttributesService.service';
export * from './ledgerDetailLineService.service';
import { LedgerDetailLineServiceService } from './ledgerDetailLineService.service';
export * from './ledgerGroupImportUtilService.service';
import { LedgerGroupImportUtilServiceService } from './ledgerGroupImportUtilService.service';
export * from './ledgerGroupService.service';
import { LedgerGroupServiceService } from './ledgerGroupService.service';
export * from './ledgerImportExportUtilService.service';
import { LedgerImportExportUtilServiceService } from './ledgerImportExportUtilService.service';
export * from './ledgerItemDefaultsService.service';
import { LedgerItemDefaultsServiceService } from './ledgerItemDefaultsService.service';
export * from './ledgerItemDiscountService.service';
import { LedgerItemDiscountServiceService } from './ledgerItemDiscountService.service';
export * from './ledgerItemGroupDiscountService.service';
import { LedgerItemGroupDiscountServiceService } from './ledgerItemGroupDiscountService.service';
export * from './ledgerItemSingleEntryService.service';
import { LedgerItemSingleEntryServiceService } from './ledgerItemSingleEntryService.service';
export * from './ledgerLabelService.service';
import { LedgerLabelServiceService } from './ledgerLabelService.service';
export * from './ledgerPurchaseSummaryReportService.service';
import { LedgerPurchaseSummaryReportServiceService } from './ledgerPurchaseSummaryReportService.service';
export * from './ledgerReportPrintService.service';
import { LedgerReportPrintServiceService } from './ledgerReportPrintService.service';
export * from './ledgerReportService.service';
import { LedgerReportServiceService } from './ledgerReportService.service';
export * from './ledgerSaleSummaryReportService.service';
import { LedgerSaleSummaryReportServiceService } from './ledgerSaleSummaryReportService.service';
export * from './ledgerService.service';
import { LedgerServiceService } from './ledgerService.service';
export * from './ledgerWiseTaxSummaryReportService.service';
import { LedgerWiseTaxSummaryReportServiceService } from './ledgerWiseTaxSummaryReportService.service';
export * from './licenseManagerService.service';
import { LicenseManagerServiceService } from './licenseManagerService.service';
export * from './licenseService.service';
import { LicenseServiceService } from './licenseService.service';
export * from './loginService.service';
import { LoginServiceService } from './loginService.service';
export * from './malkhataReportService.service';
import { MalkhataReportServiceService } from './malkhataReportService.service';
export * from './mandiService.service';
import { MandiServiceService } from './mandiService.service';
export * from './manufactureWiseSaleSummaryReportService.service';
import { ManufactureWiseSaleSummaryReportServiceService } from './manufactureWiseSaleSummaryReportService.service';
export * from './manufactureWiseStockSummaryReportService.service';
import { ManufactureWiseStockSummaryReportServiceService } from './manufactureWiseStockSummaryReportService.service';
export * from './manufacturerService.service';
import { ManufacturerServiceService } from './manufacturerService.service';
export * from './materialIssueRegisterService.service';
import { MaterialIssueRegisterServiceService } from './materialIssueRegisterService.service';
export * from './materialIssueTxService.service';
import { MaterialIssueTxServiceService } from './materialIssueTxService.service';
export * from './materialRequestRegisterService.service';
import { MaterialRequestRegisterServiceService } from './materialRequestRegisterService.service';
export * from './materialRequestTxService.service';
import { MaterialRequestTxServiceService } from './materialRequestTxService.service';
export * from './materialRequestTxStatusHistoryService.service';
import { MaterialRequestTxStatusHistoryServiceService } from './materialRequestTxStatusHistoryService.service';
export * from './milkSaleReportService.service';
import { MilkSaleReportServiceService } from './milkSaleReportService.service';
export * from './moduleService.service';
import { ModuleServiceService } from './moduleService.service';
export * from './monthlyLedgerAnalysisReportService.service';
import { MonthlyLedgerAnalysisReportServiceService } from './monthlyLedgerAnalysisReportService.service';
export * from './multiTransactionService.service';
import { MultiTransactionServiceService } from './multiTransactionService.service';
export * from './narrationService.service';
import { NarrationServiceService } from './narrationService.service';
export * from './notesService.service';
import { NotesServiceService } from './notesService.service';
export * from './notificationService.service';
import { NotificationServiceService } from './notificationService.service';
export * from './nucleusProductService.service';
import { NucleusProductServiceService } from './nucleusProductService.service';
export * from './openCartOrderService.service';
import { OpenCartOrderServiceService } from './openCartOrderService.service';
export * from './openingBalanceTxService.service';
import { OpeningBalanceTxServiceService } from './openingBalanceTxService.service';
export * from './openingStockTxService.service';
import { OpeningStockTxServiceService } from './openingStockTxService.service';
export * from './operationalTaskService.service';
import { OperationalTaskServiceService } from './operationalTaskService.service';
export * from './organizationService.service';
import { OrganizationServiceService } from './organizationService.service';
export * from './organizationStockSummaryItemReportService.service';
import { OrganizationStockSummaryItemReportServiceService } from './organizationStockSummaryItemReportService.service';
export * from './organizationSubCompanyList.service';
import { OrganizationSubCompanyListService } from './organizationSubCompanyList.service';
export * from './otherChargesService.service';
import { OtherChargesServiceService } from './otherChargesService.service';
export * from './outstandingReportService.service';
import { OutstandingReportServiceService } from './outstandingReportService.service';
export * from './overstockReportService.service';
import { OverstockReportServiceService } from './overstockReportService.service';
export * from './pInventoryOrderTxService.service';
import { PInventoryOrderTxServiceService } from './pInventoryOrderTxService.service';
export * from './pOOutwardTxService.service';
import { POOutwardTxServiceService } from './pOOutwardTxService.service';
export * from './pOTxService.service';
import { POTxServiceService } from './pOTxService.service';
export * from './partnerItemInfoService.service';
import { PartnerItemInfoServiceService } from './partnerItemInfoService.service';
export * from './partnerItemLicenseGenerationService.service';
import { PartnerItemLicenseGenerationServiceService } from './partnerItemLicenseGenerationService.service';
export * from './partnerItemLicenseReportService.service';
import { PartnerItemLicenseReportServiceService } from './partnerItemLicenseReportService.service';
export * from './partyWiseDailyReceiptReportService.service';
import { PartyWiseDailyReceiptReportServiceService } from './partyWiseDailyReceiptReportService.service';
export * from './paymentLinkService.service';
import { PaymentLinkServiceService } from './paymentLinkService.service';
export * from './paymentModeReportService.service';
import { PaymentModeReportServiceService } from './paymentModeReportService.service';
export * from './paymentModeService.service';
import { PaymentModeServiceService } from './paymentModeService.service';
export * from './paymentTxService.service';
import { PaymentTxServiceService } from './paymentTxService.service';
export * from './pendingCFormListService.service';
import { PendingCFormListServiceService } from './pendingCFormListService.service';
export * from './pendingOutwardPOTxReportService.service';
import { PendingOutwardPOTxReportServiceService } from './pendingOutwardPOTxReportService.service';
export * from './pendingPOTxReportService.service';
import { PendingPOTxReportServiceService } from './pendingPOTxReportService.service';
export * from './priceListPrintingReportService.service';
import { PriceListPrintingReportServiceService } from './priceListPrintingReportService.service';
export * from './priceListPrintingReportService2.service';
import { PriceListPrintingReportService2Service } from './priceListPrintingReportService2.service';
export * from './printAttributesListService.service';
import { PrintAttributesListServiceService } from './printAttributesListService.service';
export * from './printBarCodeService.service';
import { PrintBarCodeServiceService } from './printBarCodeService.service';
export * from './printLedgerLabelsService.service';
import { PrintLedgerLabelsServiceService } from './printLedgerLabelsService.service';
export * from './printMeasurementsListService.service';
import { PrintMeasurementsListServiceService } from './printMeasurementsListService.service';
export * from './printSettingService.service';
import { PrintSettingServiceService } from './printSettingService.service';
export * from './procurementRequestRegisterService.service';
import { ProcurementRequestRegisterServiceService } from './procurementRequestRegisterService.service';
export * from './procurementRequestTxService.service';
import { ProcurementRequestTxServiceService } from './procurementRequestTxService.service';
export * from './procurementRequestTxStatusHistoryService.service';
import { ProcurementRequestTxStatusHistoryServiceService } from './procurementRequestTxStatusHistoryService.service';
export * from './productRegistrationService.service';
import { ProductRegistrationServiceService } from './productRegistrationService.service';
export * from './productUserLedgerService.service';
import { ProductUserLedgerServiceService } from './productUserLedgerService.service';
export * from './productUserService.service';
import { ProductUserServiceService } from './productUserService.service';
export * from './productionDetailItemReportService.service';
import { ProductionDetailItemReportServiceService } from './productionDetailItemReportService.service';
export * from './productionItemSummaryReportService.service';
import { ProductionItemSummaryReportServiceService } from './productionItemSummaryReportService.service';
export * from './productionItemSummaryReportService2.service';
import { ProductionItemSummaryReportService2Service } from './productionItemSummaryReportService2.service';
export * from './productionTxService.service';
import { ProductionTxServiceService } from './productionTxService.service';
export * from './profitLossReportService.service';
import { ProfitLossReportServiceService } from './profitLossReportService.service';
export * from './proformaRefundTxService.service';
import { ProformaRefundTxServiceService } from './proformaRefundTxService.service';
export * from './proformaTxService.service';
import { ProformaTxServiceService } from './proformaTxService.service';
export * from './publicNotificationService.service';
import { PublicNotificationServiceService } from './publicNotificationService.service';
export * from './purchaseAnalysisReportService.service';
import { PurchaseAnalysisReportServiceService } from './purchaseAnalysisReportService.service';
export * from './purchaseDetailService.service';
import { PurchaseDetailServiceService } from './purchaseDetailService.service';
export * from './purchaseEnquiryTxReportService.service';
import { PurchaseEnquiryTxReportServiceService } from './purchaseEnquiryTxReportService.service';
export * from './purchaseEnquiryTxService.service';
import { PurchaseEnquiryTxServiceService } from './purchaseEnquiryTxService.service';
export * from './purchaseItemReportService.service';
import { PurchaseItemReportServiceService } from './purchaseItemReportService.service';
export * from './purchaseOrderTxPendingPaymentReportService.service';
import { PurchaseOrderTxPendingPaymentReportServiceService } from './purchaseOrderTxPendingPaymentReportService.service';
export * from './purchaseOrderTxService.service';
import { PurchaseOrderTxServiceService } from './purchaseOrderTxService.service';
export * from './purchaseReturnOrderTxService.service';
import { PurchaseReturnOrderTxServiceService } from './purchaseReturnOrderTxService.service';
export * from './qCParameterService.service';
import { QCParameterServiceService } from './qCParameterService.service';
export * from './qCStatusTxService.service';
import { QCStatusTxServiceService } from './qCStatusTxService.service';
export * from './quotationTxReportService.service';
import { QuotationTxReportServiceService } from './quotationTxReportService.service';
export * from './quotationTxService.service';
import { QuotationTxServiceService } from './quotationTxService.service';
export * from './receiptTxService.service';
import { ReceiptTxServiceService } from './receiptTxService.service';
export * from './recoverDataService.service';
import { RecoverDataServiceService } from './recoverDataService.service';
export * from './redefineVoucherNumberService.service';
import { RedefineVoucherNumberServiceService } from './redefineVoucherNumberService.service';
export * from './repairDeliveryTxService.service';
import { RepairDeliveryTxServiceService } from './repairDeliveryTxService.service';
export * from './repairItemService.service';
import { RepairItemServiceService } from './repairItemService.service';
export * from './repairItemSummaryService.service';
import { RepairItemSummaryServiceService } from './repairItemSummaryService.service';
export * from './repairRequestAttributeGroupLineService.service';
import { RepairRequestAttributeGroupLineServiceService } from './repairRequestAttributeGroupLineService.service';
export * from './repairRequestItemLineService.service';
import { RepairRequestItemLineServiceService } from './repairRequestItemLineService.service';
export * from './repairRequestLineNotesService.service';
import { RepairRequestLineNotesServiceService } from './repairRequestLineNotesService.service';
export * from './repairRequestLineService.service';
import { RepairRequestLineServiceService } from './repairRequestLineService.service';
export * from './repairRequestReportService.service';
import { RepairRequestReportServiceService } from './repairRequestReportService.service';
export * from './repairRequestReportService2.service';
import { RepairRequestReportService2Service } from './repairRequestReportService2.service';
export * from './repairRequestReportService3.service';
import { RepairRequestReportService3Service } from './repairRequestReportService3.service';
export * from './repairRequestTxService.service';
import { RepairRequestTxServiceService } from './repairRequestTxService.service';
export * from './repairServiceCenterDeliveryLineService.service';
import { RepairServiceCenterDeliveryLineServiceService } from './repairServiceCenterDeliveryLineService.service';
export * from './repairServiceCenterDeliveryTxService.service';
import { RepairServiceCenterDeliveryTxServiceService } from './repairServiceCenterDeliveryTxService.service';
export * from './repairServiceCenterLineService.service';
import { RepairServiceCenterLineServiceService } from './repairServiceCenterLineService.service';
export * from './repairServiceCenterTxService.service';
import { RepairServiceCenterTxServiceService } from './repairServiceCenterTxService.service';
export * from './repairTemplateListPrefService.service';
import { RepairTemplateListPrefServiceService } from './repairTemplateListPrefService.service';
export * from './requestFeatureService.service';
import { RequestFeatureServiceService } from './requestFeatureService.service';
export * from './restaurantCancelOrderService.service';
import { RestaurantCancelOrderServiceService } from './restaurantCancelOrderService.service';
export * from './restaurantTableOrderLineService.service';
import { RestaurantTableOrderLineServiceService } from './restaurantTableOrderLineService.service';
export * from './restaurantTableService.service';
import { RestaurantTableServiceService } from './restaurantTableService.service';
export * from './routeService.service';
import { RouteServiceService } from './routeService.service';
export * from './sMSHostedService.service';
import { SMSHostedServiceService } from './sMSHostedService.service';
export * from './sMSInfoService.service';
import { SMSInfoServiceService } from './sMSInfoService.service';
export * from './sMSPlanReportService.service';
import { SMSPlanReportServiceService } from './sMSPlanReportService.service';
export * from './sMSPlanService.service';
import { SMSPlanServiceService } from './sMSPlanService.service';
export * from './sMSUtilService.service';
import { SMSUtilServiceService } from './sMSUtilService.service';
export * from './saleAnalysisReportService.service';
import { SaleAnalysisReportServiceService } from './saleAnalysisReportService.service';
export * from './saleBillPrintService.service';
import { SaleBillPrintServiceService } from './saleBillPrintService.service';
export * from './saleCampaignService.service';
import { SaleCampaignServiceService } from './saleCampaignService.service';
export * from './saleDataJsonService.service';
import { SaleDataJsonServiceService } from './saleDataJsonService.service';
export * from './saleDetailService.service';
import { SaleDetailServiceService } from './saleDetailService.service';
export * from './saleEnquiryTxReportService.service';
import { SaleEnquiryTxReportServiceService } from './saleEnquiryTxReportService.service';
export * from './saleEnquiryTxService.service';
import { SaleEnquiryTxServiceService } from './saleEnquiryTxService.service';
export * from './saleOrderTxPendingReceiptReportService.service';
import { SaleOrderTxPendingReceiptReportServiceService } from './saleOrderTxPendingReceiptReportService.service';
export * from './saleOrderTxService.service';
import { SaleOrderTxServiceService } from './saleOrderTxService.service';
export * from './saleReturnOrderTxService.service';
import { SaleReturnOrderTxServiceService } from './saleReturnOrderTxService.service';
export * from './saleSourceService.service';
import { SaleSourceServiceService } from './saleSourceService.service';
export * from './saleSummaryReportService.service';
import { SaleSummaryReportServiceService } from './saleSummaryReportService.service';
export * from './saleTicketDetailsService.service';
import { SaleTicketDetailsServiceService } from './saleTicketDetailsService.service';
export * from './salesChallanTxAttributesService.service';
import { SalesChallanTxAttributesServiceService } from './salesChallanTxAttributesService.service';
export * from './salesManReportService.service';
import { SalesManReportServiceService } from './salesManReportService.service';
export * from './salesManService.service';
import { SalesManServiceService } from './salesManService.service';
export * from './salesSaleTxAttributesService.service';
import { SalesSaleTxAttributesServiceService } from './salesSaleTxAttributesService.service';
export * from './searchVoucherService.service';
import { SearchVoucherServiceService } from './searchVoucherService.service';
export * from './sectionService.service';
import { SectionServiceService } from './sectionService.service';
export * from './securityManagerService.service';
import { SecurityManagerServiceService } from './securityManagerService.service';
export * from './serviceCenterRequestReportService.service';
import { ServiceCenterRequestReportServiceService } from './serviceCenterRequestReportService.service';
export * from './serviceGroupService.service';
import { ServiceGroupServiceService } from './serviceGroupService.service';
export * from './serviceOrderTxService.service';
import { ServiceOrderTxServiceService } from './serviceOrderTxService.service';
export * from './servicePrintService.service';
import { ServicePrintServiceService } from './servicePrintService.service';
export * from './servicePrintSettingService.service';
import { ServicePrintSettingServiceService } from './servicePrintSettingService.service';
export * from './serviceService.service';
import { ServiceServiceService } from './serviceService.service';
export * from './serviceTxService.service';
import { ServiceTxServiceService } from './serviceTxService.service';
export * from './sessionService.service';
import { SessionServiceService } from './sessionService.service';
export * from './shellerRegisterService.service';
import { ShellerRegisterServiceService } from './shellerRegisterService.service';
export * from './showShelfLocationService.service';
import { ShowShelfLocationServiceService } from './showShelfLocationService.service';
export * from './signUpEComService.service';
import { SignUpEComServiceService } from './signUpEComService.service';
export * from './siteService.service';
import { SiteServiceService } from './siteService.service';
export * from './standardInventoryTxReportService.service';
import { StandardInventoryTxReportServiceService } from './standardInventoryTxReportService.service';
export * from './startupDataService.service';
import { StartupDataServiceService } from './startupDataService.service';
export * from './stateService.service';
import { StateServiceService } from './stateService.service';
export * from './stitchingCategoryService.service';
import { StitchingCategoryServiceService } from './stitchingCategoryService.service';
export * from './stitchingCustomerService.service';
import { StitchingCustomerServiceService } from './stitchingCustomerService.service';
export * from './stitchingDeliveryLineService.service';
import { StitchingDeliveryLineServiceService } from './stitchingDeliveryLineService.service';
export * from './stitchingDeliveryTxService.service';
import { StitchingDeliveryTxServiceService } from './stitchingDeliveryTxService.service';
export * from './stitchingItemHistoryReportService.service';
import { StitchingItemHistoryReportServiceService } from './stitchingItemHistoryReportService.service';
export * from './stitchingItemLineService.service';
import { StitchingItemLineServiceService } from './stitchingItemLineService.service';
export * from './stitchingItemService.service';
import { StitchingItemServiceService } from './stitchingItemService.service';
export * from './stitchingMeasurementService.service';
import { StitchingMeasurementServiceService } from './stitchingMeasurementService.service';
export * from './stitchingOperationService.service';
import { StitchingOperationServiceService } from './stitchingOperationService.service';
export * from './stitchingReportService.service';
import { StitchingReportServiceService } from './stitchingReportService.service';
export * from './stitchingTxService.service';
import { StitchingTxServiceService } from './stitchingTxService.service';
export * from './stitchingVendorDeliveryTxService.service';
import { StitchingVendorDeliveryTxServiceService } from './stitchingVendorDeliveryTxService.service';
export * from './stitchingVendorLineService.service';
import { StitchingVendorLineServiceService } from './stitchingVendorLineService.service';
export * from './stitchingVendorReportService.service';
import { StitchingVendorReportServiceService } from './stitchingVendorReportService.service';
export * from './stitchingVendorService.service';
import { StitchingVendorServiceService } from './stitchingVendorService.service';
export * from './stitchingVendorTxService.service';
import { StitchingVendorTxServiceService } from './stitchingVendorTxService.service';
export * from './stockAttributeGroupLineService.service';
import { StockAttributeGroupLineServiceService } from './stockAttributeGroupLineService.service';
export * from './stockDetailedSummaryReportService.service';
import { StockDetailedSummaryReportServiceService } from './stockDetailedSummaryReportService.service';
export * from './stockDetailedSummaryReportService2.service';
import { StockDetailedSummaryReportService2Service } from './stockDetailedSummaryReportService2.service';
export * from './stockLevelAnalysisReportService.service';
import { StockLevelAnalysisReportServiceService } from './stockLevelAnalysisReportService.service';
export * from './stockLocationService.service';
import { StockLocationServiceService } from './stockLocationService.service';
export * from './stockLocationTypeService.service';
import { StockLocationTypeServiceService } from './stockLocationTypeService.service';
export * from './stockService.service';
import { StockServiceService } from './stockService.service';
export * from './stockShortageTxService.service';
import { StockShortageTxServiceService } from './stockShortageTxService.service';
export * from './stockSummaryIncludingChallanReportService.service';
import { StockSummaryIncludingChallanReportServiceService } from './stockSummaryIncludingChallanReportService.service';
export * from './stockSummaryReportService.service';
import { StockSummaryReportServiceService } from './stockSummaryReportService.service';
export * from './stockSummaryReportService2.service';
import { StockSummaryReportService2Service } from './stockSummaryReportService2.service';
export * from './stockSurplusTxService.service';
import { StockSurplusTxServiceService } from './stockSurplusTxService.service';
export * from './stockTakingReportService.service';
import { StockTakingReportServiceService } from './stockTakingReportService.service';
export * from './stockTakingService.service';
import { StockTakingServiceService } from './stockTakingService.service';
export * from './stockTransferReportService.service';
import { StockTransferReportServiceService } from './stockTransferReportService.service';
export * from './stockTransferTxService.service';
import { StockTransferTxServiceService } from './stockTransferTxService.service';
export * from './stockTxService.service';
import { StockTxServiceService } from './stockTxService.service';
export * from './storeService.service';
import { StoreServiceService } from './storeService.service';
export * from './storeUserService.service';
import { StoreUserServiceService } from './storeUserService.service';
export * from './storemgmtService.service';
import { StoremgmtServiceService } from './storemgmtService.service';
export * from './syncService.service';
import { SyncServiceService } from './syncService.service';
export * from './tDSCommissionService.service';
import { TDSCommissionServiceService } from './tDSCommissionService.service';
export * from './tDSGroupInterestReportService.service';
import { TDSGroupInterestReportServiceService } from './tDSGroupInterestReportService.service';
export * from './tDSInterestReportService.service';
import { TDSInterestReportServiceService } from './tDSInterestReportService.service';
export * from './tDSTypeService.service';
import { TDSTypeServiceService } from './tDSTypeService.service';
export * from './tITicketHistoryService.service';
import { TITicketHistoryServiceService } from './tITicketHistoryService.service';
export * from './tITicketService.service';
import { TITicketServiceService } from './tITicketService.service';
export * from './tITrackerService.service';
import { TITrackerServiceService } from './tITrackerService.service';
export * from './taskService.service';
import { TaskServiceService } from './taskService.service';
export * from './taxClassService.service';
import { TaxClassServiceService } from './taxClassService.service';
export * from './taxConfigurationExtensionManagerService.service';
import { TaxConfigurationExtensionManagerServiceService } from './taxConfigurationExtensionManagerService.service';
export * from './taxConfigurationService.service';
import { TaxConfigurationServiceService } from './taxConfigurationService.service';
export * from './taxGroupService.service';
import { TaxGroupServiceService } from './taxGroupService.service';
export * from './taxRateWiseSalePurchaseSummaryReportService.service';
import { TaxRateWiseSalePurchaseSummaryReportServiceService } from './taxRateWiseSalePurchaseSummaryReportService.service';
export * from './taxService.service';
import { TaxServiceService } from './taxService.service';
export * from './taxSupportedTxProviderManagerService.service';
import { TaxSupportedTxProviderManagerServiceService } from './taxSupportedTxProviderManagerService.service';
export * from './taxWiseProfitAndLossReportService.service';
import { TaxWiseProfitAndLossReportServiceService } from './taxWiseProfitAndLossReportService.service';
export * from './taxWiseSalePurchaseQuarterlySummaryReportService.service';
import { TaxWiseSalePurchaseQuarterlySummaryReportServiceService } from './taxWiseSalePurchaseQuarterlySummaryReportService.service';
export * from './taxWiseSalePurchaseSummaryReportService.service';
import { TaxWiseSalePurchaseSummaryReportServiceService } from './taxWiseSalePurchaseSummaryReportService.service';
export * from './taxWiseSaleRegisterReportService.service';
import { TaxWiseSaleRegisterReportServiceService } from './taxWiseSaleRegisterReportService.service';
export * from './taxWiseStockEvalutionSummaryService.service';
import { TaxWiseStockEvalutionSummaryServiceService } from './taxWiseStockEvalutionSummaryService.service';
export * from './taxWiseTransactionSummaryReportService.service';
import { TaxWiseTransactionSummaryReportServiceService } from './taxWiseTransactionSummaryReportService.service';
export * from './taxableEntityService.service';
import { TaxableEntityServiceService } from './taxableEntityService.service';
export * from './tentativePurchaseOrderReportService.service';
import { TentativePurchaseOrderReportServiceService } from './tentativePurchaseOrderReportService.service';
export * from './tentativePurchaseOrderService.service';
import { TentativePurchaseOrderServiceService } from './tentativePurchaseOrderService.service';
export * from './termsService.service';
import { TermsServiceService } from './termsService.service';
export * from './ticketAnalysisReportService.service';
import { TicketAnalysisReportServiceService } from './ticketAnalysisReportService.service';
export * from './ticketAnalysisReportService2.service';
import { TicketAnalysisReportService2Service } from './ticketAnalysisReportService2.service';
export * from './ticketDetailsReportService.service';
import { TicketDetailsReportServiceService } from './ticketDetailsReportService.service';
export * from './ticketDetailsReportService2.service';
import { TicketDetailsReportService2Service } from './ticketDetailsReportService2.service';
export * from './ticketItemLineService.service';
import { TicketItemLineServiceService } from './ticketItemLineService.service';
export * from './ticketPrintService.service';
import { TicketPrintServiceService } from './ticketPrintService.service';
export * from './ticketSaleMappingService.service';
import { TicketSaleMappingServiceService } from './ticketSaleMappingService.service';
export * from './ticketSmsPrefTemplateListService.service';
import { TicketSmsPrefTemplateListServiceService } from './ticketSmsPrefTemplateListService.service';
export * from './trackerSaleAttributeService.service';
import { TrackerSaleAttributeServiceService } from './trackerSaleAttributeService.service';
export * from './tradeUtilService.service';
import { TradeUtilServiceService } from './tradeUtilService.service';
export * from './tradingAccountReportService.service';
import { TradingAccountReportServiceService } from './tradingAccountReportService.service';
export * from './tradingItemReportService.service';
import { TradingItemReportServiceService } from './tradingItemReportService.service';
export * from './trainingRefundTransactionService.service';
import { TrainingRefundTransactionServiceService } from './trainingRefundTransactionService.service';
export * from './trainingTransactionService.service';
import { TrainingTransactionServiceService } from './trainingTransactionService.service';
export * from './transactionAuditReportService.service';
import { TransactionAuditReportServiceService } from './transactionAuditReportService.service';
export * from './transactionAuditService.service';
import { TransactionAuditServiceService } from './transactionAuditService.service';
export * from './transactionDocumentService.service';
import { TransactionDocumentServiceService } from './transactionDocumentService.service';
export * from './transactionPrintService.service';
import { TransactionPrintServiceService } from './transactionPrintService.service';
export * from './transactionQCStatusReportService.service';
import { TransactionQCStatusReportServiceService } from './transactionQCStatusReportService.service';
export * from './transactionStatusApprovalService.service';
import { TransactionStatusApprovalServiceService } from './transactionStatusApprovalService.service';
export * from './transactionStatusHistoryService.service';
import { TransactionStatusHistoryServiceService } from './transactionStatusHistoryService.service';
export * from './transactionStatusService.service';
import { TransactionStatusServiceService } from './transactionStatusService.service';
export * from './transactionTypeService.service';
import { TransactionTypeServiceService } from './transactionTypeService.service';
export * from './transportReportService.service';
import { TransportReportServiceService } from './transportReportService.service';
export * from './trialBalanceReportService.service';
import { TrialBalanceReportServiceService } from './trialBalanceReportService.service';
export * from './uPIQRCodeService.service';
import { UPIQRCodeServiceService } from './uPIQRCodeService.service';
export * from './understockReportService.service';
import { UnderstockReportServiceService } from './understockReportService.service';
export * from './unitService.service';
import { UnitServiceService } from './unitService.service';
export * from './unsoldItemListForGroupReportService.service';
import { UnsoldItemListForGroupReportServiceService } from './unsoldItemListForGroupReportService.service';
export * from './unsoldItemListReportService.service';
import { UnsoldItemListReportServiceService } from './unsoldItemListReportService.service';
export * from './unusedItemListService.service';
import { UnusedItemListServiceService } from './unusedItemListService.service';
export * from './unusedItemsService.service';
import { UnusedItemsServiceService } from './unusedItemsService.service';
export * from './upgradeService.service';
import { UpgradeServiceService } from './upgradeService.service';
export * from './userGroupService.service';
import { UserGroupServiceService } from './userGroupService.service';
export * from './userPreferenceService.service';
import { UserPreferenceServiceService } from './userPreferenceService.service';
export * from './vat15UtilService.service';
import { Vat15UtilServiceService } from './vat15UtilService.service';
export * from './vat23ReportService.service';
import { Vat23ReportServiceService } from './vat23ReportService.service';
export * from './vatUtilService.service';
import { VatUtilServiceService } from './vatUtilService.service';
export * from './vehicleBillPrintService.service';
import { VehicleBillPrintServiceService } from './vehicleBillPrintService.service';
export * from './vehicleChallanTxAttributesService.service';
import { VehicleChallanTxAttributesServiceService } from './vehicleChallanTxAttributesService.service';
export * from './vehicleQuotationTxAttributesService.service';
import { VehicleQuotationTxAttributesServiceService } from './vehicleQuotationTxAttributesService.service';
export * from './vehicleSaleTxAttributesService.service';
import { VehicleSaleTxAttributesServiceService } from './vehicleSaleTxAttributesService.service';
export * from './voucherConfigService.service';
import { VoucherConfigServiceService } from './voucherConfigService.service';
export * from './voucherConfigTypeService.service';
import { VoucherConfigTypeServiceService } from './voucherConfigTypeService.service';
export * from './voucherNumberService.service';
import { VoucherNumberServiceService } from './voucherNumberService.service';
export * from './voucherPrintConfigService.service';
import { VoucherPrintConfigServiceService } from './voucherPrintConfigService.service';
export * from './voucherTxService.service';
import { VoucherTxServiceService } from './voucherTxService.service';
export * from './wooCommerceOrderService.service';
import { WooCommerceOrderServiceService } from './wooCommerceOrderService.service';
export * from './workingDateUtilService.service';
import { WorkingDateUtilServiceService } from './workingDateUtilService.service';
export const APIS = [APIPurchaseDetailReportServiceService, APIPurchaseDetailServiceService, APITypeServiceService, AbstractItemServiceService, AbstractLedgerServiceService, AbstractSaleTxServiceService, AbstractTransactionServiceService, AbstractVoucherTxServiceService, AccountingBillPrintServiceService, AccountingConvertTransactionServiceService, AccountingSMSPrefTemplateListServiceService, AccountingSMSServiceService, AccountingTxReportServiceService, AddressTypeServiceService, ApplicationResourceServiceService, ApplicationUserPrivilegeServiceService, AreaImportServiceService, AreaServiceService, AssetServiceService, AttributeGroupServiceService, AttributeServiceService, BackupServiceService, BagServiceService, BagsDetailsReportServiceService, BagsDetailsReportService2Service, BalanceSheetReportServiceService, BankEntryRegisterReportServiceService, BankReconciliationReportServiceService, BankTxServiceService, BarCodePrintConfigurationServiceService, BarCodeServiceService, BarcodePrintSettingServiceService, BaseSMSPrefTemplateListServiceService, BillingClassificationServiceService, BillingGroupServiceService, BirthdayAndAnniversaryReportServiceService, BonusReportServiceService, BrokerReportServiceService, BrokerServiceService, CacheServiceService, CapitalAccountReportServiceService, CashBookReportServiceService, CashInHandReportServiceService, CashSaleReportServiceService, ChallanInwardTxServiceService, ChallanTxServiceService, ChemistItemServiceService, ChemistSaleTxAttributesServiceService, ChequeBookServiceService, ChequeConfigurationServiceService, ChequeDetailReportServiceService, ChequeDetailServiceService, ChequeSearchReportServiceService, ChoiceListServiceService, CityServiceService, ClosingRateServiceService, Code128ServiceService, CommissionReportServiceService, CommissionSaleReportServiceService, CompanyPlanServiceService, CompanyPreferenceServiceService, CompanyServiceService, CompareTaxClassWithItemMasterReportServiceService, ConsumptionItemDetailReportServiceService, ConsumptionSummaryReportServiceService, ConsumptionSummaryReportService2Service, ConsumptionTxServiceService, ContactAddressServiceService, ContactServiceService, ConvertProcurementTxPurchaseEnquriyTxServiceService, ConvertPurchaseEnquiryTransactionServiceService, ConvertPurchaseEnquiryTxServiceService, ConvertSaleEnquiryTxServiceService, ConvertTransactionServiceService, CostCenterBreakUpMonthlyLedgerGroupWiseRegisterServiceService, CostCenterBreakUpMonthlyLedgerWiseRegisterServiceService, CostCenterBreakUpRegisterServiceService, CostCenterLedgerWiseRegisterServiceService, CostCenterLineServiceService, CostCenterMonthlySummaryRegisterServiceService, CostCenterServiceService, CostCenterSummaryRegisterServiceService, CostCenterVouchersRegisterServiceService, CountryServiceService, CrNoteInvTxServiceService, CrNoteRInvTxServiceService, CrNoteTxServiceService, CrateRegisterReportServiceService, CreatePOFromStockReportServiceService, CreateRegisterReportServiceService, CredentialsServiceService, CurrentBalanceReportServiceService, CustomNamesForItemServiceService, CustomerContactServiceService, CustomerTicketServiceService, DailyEntryReportServiceService, DailyMilkCrateStockSummaryServiceService, DailyMilkPurchaseReportServiceService, DataImportHistoryServiceService, DatabaseServiceService, DayBookServiceService, DayWiseLedgerBalanceReportServiceService, DayWiseLedgerGroupBalanceReportServiceService, DeleteAllTransactionServiceService, DeleteDataAndConvertBalanceToOpeningServiceService, DeleteVerificationServiceService, DeletedTransactionReportServiceService, DeletedTransactionServiceService, DepartmentServiceService, DepreciationChartReportServiceService, DiagnosticToolServiceService, DiscountServiceService, DistrictServiceService, DoctorPrescriptionReportServiceService, DoctorServiceService, DocumentServiceService, DrNoteInvTxServiceService, DrNoteRInvTxServiceService, DrNoteTxServiceService, DrugCompositionServiceService, DueChequesReportServiceService, EComOrderServiceService, EInvoiceHostedServiceService, EInvoiceServiceService, EmailMultipleReportsUtilServiceService, EmailUtilServiceService, ErrorLogReportServiceService, ErrorLogServiceService, EventServiceService, EwayBillServiceService, ExpenseTxServiceService, ExpensesRegisterReportServiceService, ExpiringItemsReportServiceService, ExportDataServiceService, FavouriteURLServiceService, FeatureRequestServiceService, FileSharingServiceService, FindNameOrVoucherServiceService, GSTINVerificationHostedServiceService, GSTINVerificationServiceService, GSTR3ReportServiceService, GSTR4AReportServiceService, GSTReportServiceService, GatePassDetailServiceService, GatePassInTxServiceService, GatePassOutTxServiceService, GatePassOutwardTxServiceService, GenerateInvoiceServiceService, GenericReportServiceService, GrainAgentBillPrintServiceService, GrainAgentImportServiceService, GrainAgentItemRegisterReportServiceService, GrainAgentItemServiceService, GrainAgentKMSReportServiceService, GrainAgentLocalNameUtilServiceService, GrainAgentRMSReportServiceService, GrainAgentStockSummaryReportServiceService, GrainAgentStockSummaryReportService2Service, GrainPurchaseTxServiceService, GrainSaleTxServiceService, HeapRegisterServiceService, HisabKhataServiceService, HsnWiseSummaryReportServiceService, HypothecationDetailReportServiceService, IFormDetailReportServiceService, IFormTxServiceService, ImportBankEntryFromExelServiceService, ImportMilkJournalEntryFromExcelUtilServiceService, ImportMilkPurchaseFromExcelUtilServiceService, ImportTransactionExcelUtilServiceService, InActiveLedgersReportServiceService, InnoventryCustomerServiceService, InnoventryEditionInfoServiceService, InnoventryPublicServiceService, InterestReportServiceService, InterestTxServiceService, InventoryAllBillPrintServiceService, InventoryBillingGroupImportUtilServiceService, InventoryFinancialReportServiceService, InventorySMSPrefTemplateListServiceService, InventoryTransactionDashboardReportServiceService, InventoryTxReportServiceService, InventoryTxReportService2Service, InventoryTxTaxConfigurationServiceService, InventoryTxVoucherReportServiceService, InwardQuotationTxReportServiceService, InwardQuotationTxServiceService, ItemAttributeGroupLineServiceService, ItemAttributeSearchReportServiceService, ItemBatchServiceService, ItemDiscountServiceService, ItemEComServiceService, ItemGroupEComServiceService, ItemGroupQCParamReqValueServiceService, ItemGroupServiceService, ItemGroupWiseTradingAccountReportServiceService, ItemHistoryReportServiceService, ItemImportExportUtilServiceService, ItemLicenseKeyServiceService, ItemLicenseReportServiceService, ItemLineServiceService, ItemPurchaseByLedgerSummaryReportServiceService, ItemPurchaseRateAnalysisServiceService, ItemPurchaseRateVariationAnalysisReportServiceService, ItemQCParamReqValueServiceService, ItemRegisterForLedgerReportServiceService, ItemRegisterReportServiceService, ItemSaleSummaryReportServiceService, ItemSchemeLineServiceService, ItemSchemeServiceService, ItemSearchEcomServiceService, ItemSearchServiceService, ItemServiceService, ItemSupplierRateServiceService, ItemTicketDetailsServiceService, ItemTransactionParameterServiceService, ItemTransactionRegisterReportServiceService, ItemWiseLedgerSummaryReportServiceService, ItemWiseStockLocationRegisterServiceService, JFormDetailReportServiceService, JFormTxServiceService, JobWorkTxServiceService, JournalRegisterReportServiceService, JournalTxServiceService, LastTransactionInfoServiceService, LedgerAttributesServiceService, LedgerDetailLineServiceService, LedgerGroupImportUtilServiceService, LedgerGroupServiceService, LedgerImportExportUtilServiceService, LedgerItemDefaultsServiceService, LedgerItemDiscountServiceService, LedgerItemGroupDiscountServiceService, LedgerItemSingleEntryServiceService, LedgerLabelServiceService, LedgerPurchaseSummaryReportServiceService, LedgerReportPrintServiceService, LedgerReportServiceService, LedgerSaleSummaryReportServiceService, LedgerServiceService, LedgerWiseTaxSummaryReportServiceService, LicenseManagerServiceService, LicenseServiceService, LoginServiceService, MalkhataReportServiceService, MandiServiceService, ManufactureWiseSaleSummaryReportServiceService, ManufactureWiseStockSummaryReportServiceService, ManufacturerServiceService, MaterialIssueRegisterServiceService, MaterialIssueTxServiceService, MaterialRequestRegisterServiceService, MaterialRequestTxServiceService, MaterialRequestTxStatusHistoryServiceService, MilkSaleReportServiceService, ModuleServiceService, MonthlyLedgerAnalysisReportServiceService, MultiTransactionServiceService, NarrationServiceService, NotesServiceService, NotificationServiceService, NucleusProductServiceService, OpenCartOrderServiceService, OpeningBalanceTxServiceService, OpeningStockTxServiceService, OperationalTaskServiceService, OrganizationServiceService, OrganizationStockSummaryItemReportServiceService, OrganizationSubCompanyListService, OtherChargesServiceService, OutstandingReportServiceService, OverstockReportServiceService, PInventoryOrderTxServiceService, POOutwardTxServiceService, POTxServiceService, PartnerItemInfoServiceService, PartnerItemLicenseGenerationServiceService, PartnerItemLicenseReportServiceService, PartyWiseDailyReceiptReportServiceService, PaymentLinkServiceService, PaymentModeReportServiceService, PaymentModeServiceService, PaymentTxServiceService, PendingCFormListServiceService, PendingOutwardPOTxReportServiceService, PendingPOTxReportServiceService, PriceListPrintingReportServiceService, PriceListPrintingReportService2Service, PrintAttributesListServiceService, PrintBarCodeServiceService, PrintLedgerLabelsServiceService, PrintMeasurementsListServiceService, PrintSettingServiceService, ProcurementRequestRegisterServiceService, ProcurementRequestTxServiceService, ProcurementRequestTxStatusHistoryServiceService, ProductRegistrationServiceService, ProductUserLedgerServiceService, ProductUserServiceService, ProductionDetailItemReportServiceService, ProductionItemSummaryReportServiceService, ProductionItemSummaryReportService2Service, ProductionTxServiceService, ProfitLossReportServiceService, ProformaRefundTxServiceService, ProformaTxServiceService, PublicNotificationServiceService, PurchaseAnalysisReportServiceService, PurchaseDetailServiceService, PurchaseEnquiryTxReportServiceService, PurchaseEnquiryTxServiceService, PurchaseItemReportServiceService, PurchaseOrderTxPendingPaymentReportServiceService, PurchaseOrderTxServiceService, PurchaseReturnOrderTxServiceService, QCParameterServiceService, QCStatusTxServiceService, QuotationTxReportServiceService, QuotationTxServiceService, ReceiptTxServiceService, RecoverDataServiceService, RedefineVoucherNumberServiceService, RepairDeliveryTxServiceService, RepairItemServiceService, RepairItemSummaryServiceService, RepairRequestAttributeGroupLineServiceService, RepairRequestItemLineServiceService, RepairRequestLineNotesServiceService, RepairRequestLineServiceService, RepairRequestReportServiceService, RepairRequestReportService2Service, RepairRequestReportService3Service, RepairRequestTxServiceService, RepairServiceCenterDeliveryLineServiceService, RepairServiceCenterDeliveryTxServiceService, RepairServiceCenterLineServiceService, RepairServiceCenterTxServiceService, RepairTemplateListPrefServiceService, RequestFeatureServiceService, RestaurantCancelOrderServiceService, RestaurantTableOrderLineServiceService, RestaurantTableServiceService, RouteServiceService, SMSHostedServiceService, SMSInfoServiceService, SMSPlanReportServiceService, SMSPlanServiceService, SMSUtilServiceService, SaleAnalysisReportServiceService, SaleBillPrintServiceService, SaleCampaignServiceService, SaleDataJsonServiceService, SaleDetailServiceService, SaleEnquiryTxReportServiceService, SaleEnquiryTxServiceService, SaleOrderTxPendingReceiptReportServiceService, SaleOrderTxServiceService, SaleReturnOrderTxServiceService, SaleSourceServiceService, SaleSummaryReportServiceService, SaleTicketDetailsServiceService, SalesChallanTxAttributesServiceService, SalesManReportServiceService, SalesManServiceService, SalesSaleTxAttributesServiceService, SearchVoucherServiceService, SectionServiceService, SecurityManagerServiceService, ServiceCenterRequestReportServiceService, ServiceGroupServiceService, ServiceOrderTxServiceService, ServicePrintServiceService, ServicePrintSettingServiceService, ServiceServiceService, ServiceTxServiceService, SessionServiceService, ShellerRegisterServiceService, ShowShelfLocationServiceService, SignUpEComServiceService, SiteServiceService, StandardInventoryTxReportServiceService, StartupDataServiceService, StateServiceService, StitchingCategoryServiceService, StitchingCustomerServiceService, StitchingDeliveryLineServiceService, StitchingDeliveryTxServiceService, StitchingItemHistoryReportServiceService, StitchingItemLineServiceService, StitchingItemServiceService, StitchingMeasurementServiceService, StitchingOperationServiceService, StitchingReportServiceService, StitchingTxServiceService, StitchingVendorDeliveryTxServiceService, StitchingVendorLineServiceService, StitchingVendorReportServiceService, StitchingVendorServiceService, StitchingVendorTxServiceService, StockAttributeGroupLineServiceService, StockDetailedSummaryReportServiceService, StockDetailedSummaryReportService2Service, StockLevelAnalysisReportServiceService, StockLocationServiceService, StockLocationTypeServiceService, StockServiceService, StockShortageTxServiceService, StockSummaryIncludingChallanReportServiceService, StockSummaryReportServiceService, StockSummaryReportService2Service, StockSurplusTxServiceService, StockTakingReportServiceService, StockTakingServiceService, StockTransferReportServiceService, StockTransferTxServiceService, StockTxServiceService, StoreServiceService, StoreUserServiceService, StoremgmtServiceService, SyncServiceService, TDSCommissionServiceService, TDSGroupInterestReportServiceService, TDSInterestReportServiceService, TDSTypeServiceService, TITicketHistoryServiceService, TITicketServiceService, TITrackerServiceService, TaskServiceService, TaxClassServiceService, TaxConfigurationExtensionManagerServiceService, TaxConfigurationServiceService, TaxGroupServiceService, TaxRateWiseSalePurchaseSummaryReportServiceService, TaxServiceService, TaxSupportedTxProviderManagerServiceService, TaxWiseProfitAndLossReportServiceService, TaxWiseSalePurchaseQuarterlySummaryReportServiceService, TaxWiseSalePurchaseSummaryReportServiceService, TaxWiseSaleRegisterReportServiceService, TaxWiseStockEvalutionSummaryServiceService, TaxWiseTransactionSummaryReportServiceService, TaxableEntityServiceService, TentativePurchaseOrderReportServiceService, TentativePurchaseOrderServiceService, TermsServiceService, TicketAnalysisReportServiceService, TicketAnalysisReportService2Service, TicketDetailsReportServiceService, TicketDetailsReportService2Service, TicketItemLineServiceService, TicketPrintServiceService, TicketSaleMappingServiceService, TicketSmsPrefTemplateListServiceService, TrackerSaleAttributeServiceService, TradeUtilServiceService, TradingAccountReportServiceService, TradingItemReportServiceService, TrainingRefundTransactionServiceService, TrainingTransactionServiceService, TransactionAuditReportServiceService, TransactionAuditServiceService, TransactionDocumentServiceService, TransactionPrintServiceService, TransactionQCStatusReportServiceService, TransactionStatusApprovalServiceService, TransactionStatusHistoryServiceService, TransactionStatusServiceService, TransactionTypeServiceService, TransportReportServiceService, TrialBalanceReportServiceService, UPIQRCodeServiceService, UnderstockReportServiceService, UnitServiceService, UnsoldItemListForGroupReportServiceService, UnsoldItemListReportServiceService, UnusedItemListServiceService, UnusedItemsServiceService, UpgradeServiceService, UserGroupServiceService, UserPreferenceServiceService, Vat15UtilServiceService, Vat23ReportServiceService, VatUtilServiceService, VehicleBillPrintServiceService, VehicleChallanTxAttributesServiceService, VehicleQuotationTxAttributesServiceService, VehicleSaleTxAttributesServiceService, VoucherConfigServiceService, VoucherConfigTypeServiceService, VoucherNumberServiceService, VoucherPrintConfigServiceService, VoucherTxServiceService, WooCommerceOrderServiceService, WorkingDateUtilServiceService];
