/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ConvertTransactionServiceCopyMultipleTransaction } from '../model/convertTransactionServiceCopyMultipleTransaction';
import { ConvertTransactionServiceCopyTransaction } from '../model/convertTransactionServiceCopyTransaction';
import { IAbstractInventoryOrderTx } from '../model/iAbstractInventoryOrderTx';
import { IVoucherTx } from '../model/iVoucherTx';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ConvertTransactionServiceService {

    protected basePath = '/rest';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * copyMultipleTransaction
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public copyMultipleTransaction(body?: ConvertTransactionServiceCopyMultipleTransaction, observe?: 'body', reportProgress?: boolean): Observable<IAbstractInventoryOrderTx>;
    public copyMultipleTransaction(body?: ConvertTransactionServiceCopyMultipleTransaction, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IAbstractInventoryOrderTx>>;
    public copyMultipleTransaction(body?: ConvertTransactionServiceCopyMultipleTransaction, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IAbstractInventoryOrderTx>>;
    public copyMultipleTransaction(body?: ConvertTransactionServiceCopyMultipleTransaction, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<IAbstractInventoryOrderTx>('post',`${this.basePath}/admin/inventory/ConvertTransactionService/copyMultipleTransaction`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * copyTransaction
     * 
     * @param source 
     * @param target 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public copyTransaction(source?: number, target?: string, observe?: 'body', reportProgress?: boolean): Observable<IVoucherTx>;
    public copyTransaction(source?: number, target?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IVoucherTx>>;
    public copyTransaction(source?: number, target?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IVoucherTx>>;
    public copyTransaction(source?: number, target?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (source !== undefined && source !== null) {
            queryParameters = queryParameters.set('source', <any>source);
        }
        if (target !== undefined && target !== null) {
            queryParameters = queryParameters.set('target', <any>target);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<IVoucherTx>('get',`${this.basePath}/admin/accounting/ConvertTransactionService/copyTransaction`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * copyTransaction
     * 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public copyTransaction_1(body?: ConvertTransactionServiceCopyTransaction, observe?: 'body', reportProgress?: boolean): Observable<IAbstractInventoryOrderTx>;
    public copyTransaction_1(body?: ConvertTransactionServiceCopyTransaction, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IAbstractInventoryOrderTx>>;
    public copyTransaction_1(body?: ConvertTransactionServiceCopyTransaction, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IAbstractInventoryOrderTx>>;
    public copyTransaction_1(body?: ConvertTransactionServiceCopyTransaction, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<IAbstractInventoryOrderTx>('post',`${this.basePath}/admin/inventory/ConvertTransactionService/copyTransaction`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
