/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface IChequeConfiguration { 
    fontSizePrintName?: number;
    topPositionPrintDate?: number;
    fontSizePrintAmount?: number;
    printBankAccountNumber?: boolean;
    leftPositionPrintDate?: number;
    printAccountPayee?: boolean;
    fontSizePrintDate?: number;
    leftPositionPrintName?: number;
    printSignatory?: boolean;
    fontSizeAmountInWords?: number;
    topPositionPrintName?: number;
    useBoxesInDate?: boolean;
    leftPositionPrintBankAccountNumber?: number;
    fontSizePrintBankAccountNumber?: number;
    topPositionPrintBankAccountNumber?: number;
    topPositionPrintSignatory?: number;
    leftPositionPrintSignatory?: number;
    topPositionPrintAccountPayee?: number;
    fontSizePrintAccountPayee?: number;
    leftPositionPrintAccountPayee?: number;
    topPositionPrintAmount?: number;
    leftPositionPrintAmount?: number;
    topPositionAmountInWords?: number;
    fontSizePrintSignatory?: number;
    leftPositionAmountInWords?: number;
    printName?: boolean;
    boxWidth?: number;
    printDate?: boolean;
    signatory?: string;
    printAmount?: boolean;
    amountInWords?: boolean;
    name?: string;
    description?: string;
    modificationdate?: Date;
    impCompanyGuid?: string;
    productUserName?: string;
    productUserId?: number;
    logInfo?: string;
    importedId?: number;
    creationdate?: Date;
    id?: number;
    jacksontype?: string;
}