/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IIFormItemLine } from './iIFormItemLine';
import { ILedgerDetailLine } from './iLedgerDetailLine';
import { IStockDetailLine } from './iStockDetailLine';
import { ReferenceTxInfo } from './referenceTxInfo';
import { ResourceProxy } from './resourceProxy';

export interface IIFormTx { 
    itemLines?: Array<IIFormItemLine>;
    ledgerDetailLines?: Array<ILedgerDetailLine>;
    totalGrossAmount?: number;
    totalCommission?: number;
    totalWeighting?: number;
    totalStitching?: number;
    totalVyaparMadal?: number;
    totalGaushalla?: number;
    ledgerName?: string;
    ledgerId?: number;
    mandiId?: number;
    totalTotal?: number;
    newIJformFlag?: boolean;
    totalLoading?: number;
    totalBonous?: number;
    itemLineTotal?: number;
    mandiName?: string;
    totalMarket?: number;
    ijformFlag?: boolean;
    totalRDF?: number;
    totalPIDF?: number;
    voucherConfigType?: number;
    generatedVchNumSeq?: number;
    voucherConfigTypeName?: string;
    tdsTypeWithPan?: boolean;
    vouchernumber?: string;
    tdsTypeId?: number;
    tdsTypeName?: string;
    tdsRate?: number;
    typeName?: string;
    description?: string;
    transactionType?: number;
    transactiondate?: Date;
    otherReferences?: string;
    referenceTxInfoList?: Array<ReferenceTxInfo>;
    storeName?: string;
    storeId?: number;
    referenceNo?: string;
    termsId?: number;
    resourceProxy?: ResourceProxy;
    txStatus?: number;
    modificationdate?: Date;
    impCompanyGuid?: string;
    productUserName?: string;
    productUserId?: number;
    logInfo?: string;
    importedId?: number;
    creationdate?: Date;
    id?: number;
    jacksontype?: string;
    stockDetailLines?: Array<IStockDetailLine>;
}